### ISSUE TITLE
Where I can find the output epub files.

### ISSUE THREAD

**Issue by guptamohit004** [gongzhang/you-dont-know-js-epub#2]
After running the mentioned commands-
Ouput is-
Preparing...
Generating: Get Started...
Generating: Scope & Closures...
Generating: this & Object Prototypes...
Generating: Types & Grammar...
Generating: Async & Performance...
Generating: ES6 & Beyond...
Done.

But I don't know where this files are located.
Please help, never worked with Docker before this

**Comment by gongzhang** [comment]
The generated epub files is located within the container, and they are not accessible from outside by default. But you can **map a directory into the container** so you can access them.

Suppose you want to output the file to the folder `/Users/gong/My Output Folder`, then execute the command like this:

```shell
docker run --rm -it -v "/Users/gong/My Output Folder/output:/root/output" gongzhang/ydkjs-epub
```

You don't need to change the path following colon (`/root/output`) because that one is the fixed path used inside the container.

Alternatively, you can use the environment variable `$PWD` to map the current working directory so that the files will be generated into current directory. But this may only work on Unix-like systems (not sure 🤔).

```
docker run --rm -it -v $PWD/output:/root/output ydkjs-epub
```

**Comment by guptamohit004** [comment]
It worked, Thank you
